CREATE DATABASE SouthWest_DB;
USE DATABASE SouthWest_DB;

CREATE SCHEMA my_schema;
USE SCHEMA my_schema;

SELECT * FROM SOUTHWEST_TABLE;

DESC TABLE SOUTHWEST_TABLE;

-- Which services exhibit the highest and lowest listed charges?
-- HIGHEST PRICE
SELECT DESCRIPTION,
CODE_1,
CODE_1_TYPE,
SETTING,
STANDARD_CHARGE_GROSS
FROM SOUTHWEST_TABLE
WHERE STANDARD_CHARGE_GROSS IS NOT NULL
ORDER BY STANDARD_CHARGE_GROSS DESC
LIMIT 10
;

-- LOWEST PRICE
SELECT DESCRIPTION,
CODE_1,
CODE_1_TYPE,
SETTING,
STANDARD_CHARGE_GROSS
FROM SOUTHWEST_TABLE
WHERE STANDARD_CHARGE_GROSS IS NOT NULL
ORDER BY STANDARD_CHARGE_GROSS 
LIMIT 10
;

-- Where is the gap between gross and discounted cash pricing the largest?

SELECT DESCRIPTION,
CODE_1,
CODE_1_TYPE,
SETTING,
STANDARD_CHARGE_GROSS,
STANDARD_CHARGE_DISCOUNTED_CASH,

(STANDARD_CHARGE_GROSS-STANDARD_CHARGE_DISCOUNTED_CASH)AS CASH_DISCOUNT_AMOUNT,

ROUND((STANDARD_CHARGE_GROSS-STANDARD_CHARGE_DISCOUNTED_CASH)/STANDARD_CHARGE_GROSS*100,2) AS CASH_DISCOUNT_PCT
FROM SOUTHWEST_TABLE

WHERE STANDARD_CHARGE_GROSS IS NOT NULL
AND STANDARD_CHARGE_DISCOUNTED_CASH IS NOT NULL 
AND STANDARD_CHARGE_GROSS>0

ORDER BY CASH_DISCOUNT_PCT DESC
LIMIT 20
;

-- Which services show the widest negotiated price variation?

SELECT 
DESCRIPTION,
CODE_1,
CODE_1_TYPE,
SETTING,
STANDARD_CHARGE_MIN,
STANDARD_CHARGE_MAX,
(STANDARD_CHARGE_MAX-STANDARD_CHARGE_MIN) AS PRICE_RANGE
FROM SOUTHWEST_TABLE
WHERE STANDARD_CHARGE_MIN IS NOT NULL
AND STANDARD_CHARGE_MAX IS NOT NULL
ORDER BY PRICE_RANGE DESC
LIMIT 10
;

-- How do pricing patterns differ across care settings?

SELECT 
SETTING,
COUNT(*) AS TOTAL_RECORDS,
AVG(STANDARD_CHARGE_GROSS) AS AVG_GROSS_CHARGE,
AVG(STANDARD_CHARGE_DISCOUNTED_CASH) AS AVG_DISCOUNTED_CASH,
AVG(STANDARD_CHARGE_MIN) AS AVG_MIN_CHARGE,
AVG(STANDARD_CHARGE_MAX) AS AVG_MAX_CHARGE,
AVG(STANDARD_CHARGE_MAX-STANDARD_CHARGE_MIN) AS AVG_PRICE_RANGE
FROM SOUTHWEST_TABLE
WHERE SETTING IS NOT NULL
GROUP BY SETTING
ORDER BY AVG_GROSS_CHARGE DESC
;

-- How do pricing patterns differ across coding categories?

SELECT 
CODE_1_TYPE,
COUNT(*) AS TOTAL_RECORDS,
AVG(STANDARD_CHARGE_GROSS) AS AVG_GROSS_CHARGE,
AVG(STANDARD_CHARGE_DISCOUNTED_CASH) AS AVG_DISCOUNTED_CASH,
AVG(STANDARD_CHARGE_MIN) AS AVG_MIN_CHARGE,
AVG(STANDARD_CHARGE_MAX) AS AVG_MAX_CHARGE,
AVG(STANDARD_CHARGE_MAX-STANDARD_CHARGE_MIN) AS AVG_PRICE_RANGE
FROM SOUTHWEST_TABLE
WHERE CODE_1_TYPE IS NOT NULL
GROUP BY CODE_1_TYPE
ORDER BY AVG_GROSS_CHARGE DESC
;

-- FINAL 
SELECT
    DESCRIPTION,
    AVG(STANDARD_CHARGE_GROSS) AS AVG_GROSS_CHARGE,
    AVG(STANDARD_CHARGE_DISCOUNTED_CASH) AS AVG_DISCOUNTED_CASH,
    AVG(STANDARD_CHARGE_MAX - STANDARD_CHARGE_MIN) AS AVG_PRICE_RANGE,
    COUNT(*) AS RECORD_COUNT
FROM SOUTHWEST_TABLE
WHERE STANDARD_CHARGE_GROSS IS NOT NULL
  AND STANDARD_CHARGE_DISCOUNTED_CASH IS NOT NULL
  AND STANDARD_CHARGE_MIN IS NOT NULL
  AND STANDARD_CHARGE_MAX IS NOT NULL
GROUP BY DESCRIPTION
HAVING COUNT(*) >= 3
ORDER BY AVG_PRICE_RANGE DESC
LIMIT 10;

-- calculates overall average hospital charges and price variation from records with complete pricing data.

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    AVG(STANDARD_CHARGE_GROSS) AS AVG_GROSS_CHARGE,
    AVG(STANDARD_CHARGE_DISCOUNTED_CASH) AS AVG_DISCOUNTED_CASH,
    AVG(STANDARD_CHARGE_MIN) AS AVG_MIN_NEGOTIATED_CHARGE,
    AVG(STANDARD_CHARGE_MAX) AS AVG_MAX_NEGOTIATED_CHARGE,
    AVG(STANDARD_CHARGE_MAX - STANDARD_CHARGE_MIN) AS AVG_PRICE_RANGE
FROM SOUTHWEST_TABLE
WHERE STANDARD_CHARGE_GROSS IS NOT NULL
  AND STANDARD_CHARGE_DISCOUNTED_CASH IS NOT NULL
  AND STANDARD_CHARGE_MIN IS NOT NULL
  AND STANDARD_CHARGE_MAX IS NOT NULL;


  
  



